### ISSUE TITLE
MemoryError learn_bpe.py

### ISSUE THREAD

**Issue by papkov** [mt2017-tartu-shared-task/nmt-system-D#1]
cat cleaned-tc-tok-train.et cleaned-tc-tok-train.en | ../OpenNMT-py/tools/subword-nmt/learn_bpe.py -s 10000 > eten.bpe

After a few minutes:

Traceback (most recent call last):
  File "../OpenNMT-py/tools/subword-nmt/learn_bpe.py", line 250, in <module>
    main(args.input, args.output, args.symbols, args.min_frequency, args.verbose, is_dict=args.dict_input)
  File "../OpenNMT-py/tools/subword-nmt/learn_bpe.py", line 222, in main
    changes = replace_pair(most_frequent, sorted_vocab, indices)
  File "../OpenNMT-py/tools/subword-nmt/learn_bpe.py", line 166, in replace_pair
    changes.append((j, new_word, word, freq))
MemoryError

**Comment by MaksymDel** [comment]
Please, use SLURM as mentioned several times in lab1.pdf.

**Comment by MaksymDel** [comment]
From your commits, I see that you are using slurm, where changing memory and time limits as well as vocabulary size. It is the absolutely correct approach to your problem. 

Do you still get the MemoryError?

**Comment by papkov** [comment]
@maxdel I thought, slurm is only for GPU tasks, and I was wrong, sorry. Everything is fine now.

**Comment by MaksymDel** [comment]
I should definitely mention CPU case explicitly in the lab1 instructions, thank you for pointing out.
